#include "catch_amalgamated.hpp"
#include "nn/core/inference_pipeline_metrics.h"

TEST_CASE("Inference pipeline metrics expose host, graph, and RKNN stage timings", "[nn][rknn][metrics]") {
    cosmo::nn::InferencePipelineMetrics metrics;

    metrics.RecordColorConvert(2'000'000, 2);
    metrics.RecordBlobConvert(3'000'000, 2);
    metrics.RecordGraphForward(8'000'000, 2, true);
    metrics.RecordGraphForward(1'000'000, 1, false);
    metrics.RecordResultParse(4'000'000, 2, true);
    metrics.RecordResultParse(500'000, 1, false);
    constexpr auto detector = cosmo::nn::RknnModelScope::Detector;
    metrics.RecordRknnPrepare(1'000'000, detector);
    metrics.RecordRknnInputsSet(2'000'000, detector);
    metrics.RecordRknnRun(3'000'000, detector);
    metrics.RecordRknnOutputsGet(4'000'000, detector);
    metrics.RecordRknnOutputsRelease(400'000, detector);
    metrics.RecordRknnOutputTransform(5'000'000, detector);
    metrics.RecordRknnForward(15'000'000, true, detector);
    metrics.RecordRknnForward(7'000'000, false, detector);
    metrics.RecordRknnMutexWait(600'000, detector);
    metrics.RecordRknnPreprocessFastHit();
    metrics.RecordRknnRgaFill(700'000);
    metrics.RecordRknnRgaResizeColor(800'000);
    metrics.RecordRknnRgaCropResize(850'000, true);
    metrics.RecordRknnRgaCropResize(50'000, false);
    metrics.RecordRknnRgaCropSource(true);
    metrics.RecordRknnRgaCropSource(false);
    metrics.RecordRknnRgaFailure();
    metrics.RecordRknnCpuResizeFallback(900'000);
    metrics.RecordRknnCpuCropResizeFallback(950'000);
    metrics.RecordRknnCpuNormalizeFallback(1'000'000);
    metrics.RecordRknnNativeInputMap(1'100'000);
    metrics.RecordRknnInputFormat(true);
    metrics.RecordRknnInputFormat(false, true);
    metrics.RecordRknnInputFormat(false, false, true);
    metrics.RecordRknnBoundInputBind(true);
    metrics.RecordRknnBoundInputBind(false);
    metrics.RecordRknnBoundInputCopy(210'000, 1'228'800, true);
    metrics.RecordRknnBoundInputCopy(10'000, 0, false);
    metrics.RecordRknnBoundInputSync(220'000, true);
    metrics.RecordRknnBoundInputSync(20'000, false);
    metrics.RecordRknnBoundInputFrame();
    metrics.RecordRknnRgaBoundInputBind(true);
    metrics.RecordRknnRgaBoundInputBind(false);
    metrics.RecordRknnRgaBoundInputImport(30'000, true);
    metrics.RecordRknnRgaBoundInputImport(40'000, false);
    metrics.RecordRknnRgaBoundInputFrame(true);
    metrics.RecordRknnRgaBoundInputRequantize(50'000, true);
    metrics.RecordRknnRgaBoundInputRequantize(5'000, false);
    metrics.RecordRknnRgaBoundInputFrame(false);
    metrics.RecordRknnRgaBoundInputNormalizeBypass();
    metrics.RecordRknnMppDmaBufImport(60'000, true);
    metrics.RecordRknnMppDmaBufImport(7'000, false);
    metrics.RecordRknnMppDmaBufFrame(3'133'440);
    metrics.RecordRknnMppDmaBufFallback();
    metrics.RecordRknnRgaSmallFrameResize(1'200'000);
    metrics.RecordRknnRgaSmallFrameCsc(800'000);
    metrics.RecordRknnOutputFormat(true, 1'225'600);
    metrics.RecordRknnOutputFormat(false, 4'902'400, true);
    metrics.RecordRknnYolov8Transform(1'400'000, 1'500'000);
    metrics.RecordRknnYolov8DirectCandidates(true, 8'400, 17, 2'822'400, 8'000);
    metrics.RecordRknnYolov8DirectCandidates(false, 0, 0, 0);
    metrics.RecordYolov8Postprocess(1'200'000);
    metrics.RecordYolov8Nms(1'300'000);

    const auto snapshot = metrics.Snapshot();
    CHECK(snapshot.color_convert_frames == 2);
    CHECK(snapshot.color_convert_nanoseconds == 2'000'000);
    CHECK(snapshot.blob_convert_frames == 2);
    CHECK(snapshot.graph_forward_frames == 3);
    CHECK(snapshot.graph_forward_nanoseconds == 9'000'000);
    CHECK(snapshot.graph_forward_failures == 1);
    CHECK(snapshot.result_parse_frames == 3);
    CHECK(snapshot.result_parse_failures == 1);
    CHECK(snapshot.rknn_forwards == 2);
    CHECK(snapshot.rknn_forward_nanoseconds == 22'000'000);
    CHECK(snapshot.rknn_forward_failures == 1);
    CHECK(snapshot.rknn_prepare_calls == 1);
    CHECK(snapshot.rknn_inputs_set_calls == 1);
    CHECK(snapshot.rknn_run_calls == 1);
    CHECK(snapshot.rknn_outputs_get_calls == 1);
    CHECK(snapshot.rknn_outputs_release_calls == 1);
    CHECK(snapshot.rknn_outputs_release_nanoseconds == 400'000);
    CHECK(snapshot.rknn_output_transform_calls == 1);
    CHECK(snapshot.rknn_mutex_wait_calls == 1);
    CHECK(snapshot.rknn_mutex_wait_nanoseconds == 600'000);
    CHECK(snapshot.rknn_detector_forwards == 2);
    CHECK(snapshot.rknn_detector_forward_nanoseconds == 22'000'000);
    CHECK(snapshot.rknn_detector_forward_failures == 1);
    CHECK(snapshot.rknn_detector_prepare_calls == 1);
    CHECK(snapshot.rknn_detector_inputs_set_calls == 1);
    CHECK(snapshot.rknn_detector_run_calls == 1);
    CHECK(snapshot.rknn_detector_outputs_get_calls == 1);
    CHECK(snapshot.rknn_detector_outputs_release_calls == 1);
    CHECK(snapshot.rknn_detector_output_transform_calls == 1);
    CHECK(snapshot.rknn_detector_mutex_wait_calls == 1);
    CHECK(snapshot.rknn_preprocess_fast_hits == 1);
    CHECK(snapshot.rknn_rga_fill_calls == 1);
    CHECK(snapshot.rknn_rga_resize_color_calls == 1);
    CHECK(snapshot.rknn_rga_crop_resize_calls == 2);
    CHECK(snapshot.rknn_rga_crop_resize_nanoseconds == 900'000);
    CHECK(snapshot.rknn_rga_crop_resize_failures == 1);
    CHECK(snapshot.rknn_rga_crop_dmabuf_frames == 1);
    CHECK(snapshot.rknn_rga_crop_host_fallbacks == 1);
    CHECK(snapshot.rknn_rga_failures == 1);
    CHECK(snapshot.rknn_cpu_resize_fallback_calls == 1);
    CHECK(snapshot.rknn_cpu_crop_resize_fallback_calls == 1);
    CHECK(snapshot.rknn_cpu_crop_resize_fallback_nanoseconds == 950'000);
    CHECK(snapshot.rknn_cpu_normalize_fallback_calls == 1);
    CHECK(snapshot.rknn_native_input_map_calls == 1);
    CHECK(snapshot.rknn_native_int8_inputs == 1);
    CHECK(snapshot.rknn_float_inputs == 1);
    CHECK(snapshot.rknn_uint8_contract_inputs == 1);
    CHECK(snapshot.rknn_input_compatibility_fallbacks == 1);
    CHECK(snapshot.rknn_bound_input_bind_attempts == 4);
    CHECK(snapshot.rknn_bound_input_bind_failures == 2);
    CHECK(snapshot.rknn_bound_input_copy_calls == 2);
    CHECK(snapshot.rknn_bound_input_copy_nanoseconds == 220'000);
    CHECK(snapshot.rknn_bound_input_copy_bytes == 1'228'800);
    CHECK(snapshot.rknn_bound_input_copy_failures == 1);
    CHECK(snapshot.rknn_bound_input_sync_calls == 2);
    CHECK(snapshot.rknn_bound_input_sync_nanoseconds == 240'000);
    CHECK(snapshot.rknn_bound_input_sync_failures == 1);
    CHECK(snapshot.rknn_bound_input_frames == 3);
    CHECK(snapshot.rknn_rga_bound_input_bind_attempts == 2);
    CHECK(snapshot.rknn_rga_bound_input_bind_failures == 1);
    CHECK(snapshot.rknn_rga_bound_input_import_calls == 2);
    CHECK(snapshot.rknn_rga_bound_input_import_nanoseconds == 70'000);
    CHECK(snapshot.rknn_rga_bound_input_import_failures == 1);
    CHECK(snapshot.rknn_rga_bound_input_frames == 2);
    CHECK(snapshot.rknn_rga_bound_uint8_frames == 1);
    CHECK(snapshot.rknn_rga_bound_native_int8_frames == 1);
    CHECK(snapshot.rknn_rga_bound_requantize_calls == 2);
    CHECK(snapshot.rknn_rga_bound_requantize_nanoseconds == 55'000);
    CHECK(snapshot.rknn_rga_bound_requantize_failures == 1);
    CHECK(snapshot.rknn_rga_bound_input_normalize_bypasses == 1);
    CHECK(snapshot.rknn_mpp_dmabuf_import_calls == 2);
    CHECK(snapshot.rknn_mpp_dmabuf_import_nanoseconds == 67'000);
    CHECK(snapshot.rknn_mpp_dmabuf_import_failures == 1);
    CHECK(snapshot.rknn_mpp_dmabuf_frames == 1);
    CHECK(snapshot.rknn_rga_small_frame_resize_calls == 1);
    CHECK(snapshot.rknn_rga_small_frame_resize_nanoseconds == 1200000);
    CHECK(snapshot.rknn_rga_small_frame_csc_calls == 1);
    CHECK(snapshot.rknn_rga_small_frame_csc_nanoseconds == 800000);

    CHECK(snapshot.rknn_mpp_dmabuf_fallbacks == 1);
    CHECK(snapshot.rknn_mpp_dmabuf_source_bytes == 3'133'440);
    CHECK(snapshot.rknn_native_int8_outputs == 1);
    CHECK(snapshot.rknn_float_outputs == 1);
    CHECK(snapshot.rknn_output_compatibility_fallbacks == 1);
    CHECK(snapshot.rknn_native_output_bytes == 1'225'600);
    CHECK(snapshot.rknn_float_output_bytes == 4'902'400);
    CHECK(snapshot.rknn_yolov8_dfl_calls == 1);
    CHECK(snapshot.rknn_yolov8_dfl_nanoseconds == 1'400'000);
    CHECK(snapshot.rknn_yolov8_class_calls == 1);
    CHECK(snapshot.rknn_yolov8_class_nanoseconds == 1'500'000);
    CHECK(snapshot.rknn_yolov8_direct_candidate_calls == 2);
    CHECK(snapshot.rknn_yolov8_direct_candidate_failures == 1);
    CHECK(snapshot.rknn_yolov8_direct_points_scanned == 8'400);
    CHECK(snapshot.rknn_yolov8_direct_points_decoded == 17);
    CHECK(snapshot.rknn_yolov8_score_sum_points_rejected == 8'000);
    CHECK(snapshot.rknn_yolov8_logical_float_bytes_avoided == 2'822'400);
    CHECK(snapshot.yolov8_postprocess_calls == 1);
    CHECK(snapshot.yolov8_nms_calls == 1);
}
